name: epic-cron
imageNamespace: c8b80a-tools
env: dev
environment: Development
resources:
  requests:
    cpu: 100m
    memory: 100Mi
  limits:
    cpu: 250m
    memory: 200Mi
replicaCount: 1
imageTag: dev

cronTab: |
  0 1 * * * default cd /epic-cron && ./run_project_cron_submit.sh
  0 3 * * * default cd /epic-cron && ./run_project_cron_compliance.sh
  */5 * * * * default cd /epic-cron && ./run_emailer.sh
  */5 * * * * default cd /epic-cron && ./run_centre_emailer.sh
  0 17 * * 1-5 default cd /epic-cron && ./run_approved_condition.sh
  0 2 * * * default cd /epic-cron && ./run_epic_public_extractor.sh

SUBMIT:
  database:
    host: submit-patroni
    port: "5432"
  web:
    url: "https://dev.submit.eao.gov.bc.ca"
  sender:
    email: "EAO.ManagementPlanSupport@gov.bc.ca"
  staffSupportMailId: ""
  signupUrlPath: "/proponent/registration"

COMPLIANCE:
  database:
    host: compliance-patroni
    port: "5432"

TRACK:
  database:
    host: epictrack-patroni
    port: "5432"

CENTRE:
  database:
    host: centre-patroni
    port: "5432"

CONDITION:
  api:
    url: "https://condition-api-c8b80a-dev.apps.gold.devops.gov.bc.ca"
  database:
    host: condition-patroni
    port: "5432"

EPIC_PUBLIC:
  baseUrl: "https://projects.eao.gov.bc.ca"
  searchPath: "/api/public/search"
  documentTypeIds: ""
  documentTypeIdMap: ""
  maxPages: ""
  maxDocuments: ""
  enableDetailedLogs: "false"

KEYCLOAK:
  baseUrl: "https://dev.loginproxy.gov.bc.ca/auth"
  realmName: "eao-epic"

CHES:
  tokenEndpoint: "https://dev.loginproxy.gov.bc.ca/auth/realms/comsvcauth/protocol/openid-connect/token"
  apiEndpoint: "https://ches-dev.api.gov.bc.ca"
  clientId: ""
  clientSecret: ""

CLAMAV:
  host: "142.34.194.68"
  port: "16504"

secrets:
  trackDbUsername: "app"
  trackDbPassword: ""
  trackDbName: "app"
  submitDbUsername: "app"
  submitDbPassword: ""
  submitDbName: "app"
  centreDbUsername: "app"
  centreDbPassword: ""
  centreDbName: "app"
  serviceAccountId: ""
  serviceAccountSecret: ""
  conditionDbUsername: "app"
  conditionDbPassword: ""
  conditionDbName: "app"
