apiVersion: v1
kind: Secret
metadata:
  name: epic-cron
type: Opaque
data:
  # Track API URL
  track-url: {{ .Values.secrets.trackApiBaseUrl | b64enc | quote }}

  # Keycloak Base URL
  base-url: {{ .Values.secrets.keycloakBaseUrl | b64enc | quote }}

  # Keycloak Realm Name
  realm-name: {{ .Values.secrets.keycloakRealmName | b64enc | quote }}

  # Keycloak Service Account ID
  admin-username: {{ .Values.secrets.keycloakServiceAccountId | b64enc | quote }}

  # Keycloak Service Account Secret
  admin-secret: {{ .Values.secrets.keycloakServiceAccountSecret | b64enc | quote }}
