apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}
type: Opaque
data:
  # Track database credentials
  TRACK_DATABASE_USERNAME: {{ .Values.secrets.trackDbUsername | b64enc | quote }}
  TRACK_DATABASE_PASSWORD: {{ .Values.secrets.trackDbPassword | b64enc | quote }}
  TRACK_DATABASE_NAME: {{ .Values.secrets.trackDbName | b64enc | quote }}
  # Submit database credentials
  SUBMIT_DATABASE_USERNAME: {{ .Values.secrets.submitDbUsername | b64enc | quote }}
  SUBMIT_DATABASE_PASSWORD: {{ .Values.secrets.submitDbPassword | b64enc | quote }}
  SUBMIT_DATABASE_NAME: {{ .Values.secrets.submitDbName | b64enc | quote }}
  # Centre database credentials
  CENTRE_DATABASE_USERNAME: {{ .Values.secrets.centreDbUsername | b64enc | quote }}
  CENTRE_DATABASE_PASSWORD: {{ .Values.secrets.centreDbPassword | b64enc | quote }}
  CENTRE_DATABASE_NAME: {{ .Values.secrets.centreDbName | b64enc | quote }}
  # Compliance database credentials
  COMPLIANCE_DATABASE_USERNAME: {{ .Values.secrets.complianceDbUsername | b64enc | quote }}
  COMPLIANCE_DATABASE_PASSWORD: {{ .Values.secrets.complianceDbPassword | b64enc | quote }}
  COMPLIANCE_DATABASE_NAME: {{ .Values.secrets.complianceDbName | b64enc | quote }}
  # CHES credentials
  CHES_CLIENT_ID: {{ .Values.CHES.clientId | b64enc | quote }}
  CHES_CLIENT_SECRET: {{ .Values.CHES.clientSecret | b64enc | quote }}
  # Condition database credentials
  CONDITION_DATABASE_USERNAME: {{ .Values.secrets.conditionDbUsername | b64enc | quote }}
  CONDITION_DATABASE_PASSWORD: {{ .Values.secrets.conditionDbPassword | b64enc | quote }}
  CONDITION_DATABASE_NAME: {{ .Values.secrets.conditionDbName | b64enc | quote }}
  # Keycloak service account credentials
  SERVICE_ACCOUNT_ID: {{ .Values.secrets.serviceAccountId | b64enc | quote }}
  SERVICE_ACCOUNT_SECRET: {{ .Values.secrets.serviceAccountSecret | b64enc | quote }}
