apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}
type: Opaque
data:
  # Submit database credentials
  SUBMIT_DATABASE_USERNAME: {{ .Values.secrets.submitDbUsername | b64enc | quote }}
  SUBMIT_DATABASE_PASSWORD: {{ .Values.secrets.submitDbPassword | b64enc | quote }}
  SUBMIT_DATABASE_NAME: {{ .Values.secrets.submitDbName | b64enc | quote }}
  # Centre database credentials
  CENTRE_DATABASE_USERNAME: {{ .Values.secrets.centreDbUsername | b64enc | quote }}
  CENTRE_DATABASE_PASSWORD: {{ .Values.secrets.centreDbPassword | b64enc | quote }}
  CENTRE_DATABASE_NAME: {{ .Values.secrets.centreDbName | b64enc | quote }}
  # CHES credentials
  CHES_CLIENT_ID: {{ .Values.secrets.chesClientId | b64enc | quote }}
  CHES_CLIENT_SECRET: {{ .Values.secrets.chesClientSecret | b64enc | quote }}
  # Keycloak service account credentials
  KEYCLOAK_SERVICE_ACCOUNT_ID: {{ .Values.secrets.keycloakServiceAccountId | b64enc | quote }}
  KEYCLOAK_SERVICE_ACCOUNT_SECRET: {{ .Values.secrets.keycloakServiceAccountSecret | b64enc | quote }}
